// Mock data for initial UI rendering. Replaced by API calls in production.

export const CATEGORIES = ["Feature", "Bug", "Process", "Praise"];

export const feedbackItems = [
  {
    id: "f-001",
    ref: "FB-1043",
    feedbackId: "3c8e1f5a-9d27-4b06-b3e4-51a9c07d8f22",
    title: "Dark mode for the dashboard",
    description: "Late-night on-call shifts would be much easier on the eyes.",
    body: [
      "Late-night on-call shifts would be much easier on the eyes with a dark theme. The current white background is harsh at 3am.",
      "Even a simple inverted palette behind a toggle would help. Most of the team keeps the dashboard open on a second monitor all day.",
    ],
    author: "Priya S.",
    category: "FEATURE",
    sentiment: "POS",
    sentimentScores: { pos: 0.91, neu: 0.07, neg: 0.02 },
    attachment: null,
    createdAgo: "2h ago",
    createdAt: "2026-07-14T14:02:33Z",
    createdLabel: "TODAY 14:02 · 2H AGO",
  },
  {
    id: "f-002",
    ref: "FB-1042",
    feedbackId: "9f2c7a1e-4b3d-4e8a-9c21-7d5f0a6b2e14",
    title: "Uploads fail over 5 MB",
    description: "Pre-signed URL seems to expire before large PUTs complete.",
    body: [
      "Attaching anything over ~5 MB to a submission fails silently. The progress bar reaches about 80% and then resets, no error shown.",
      "It looks like the pre-signed URL expires before the PUT completes on slower connections. Smaller files upload fine. Repro: attach an 8 MB PNG on office Wi-Fi.",
    ],
    author: "Jonas K.",
    category: "BUG",
    sentiment: "NEG",
    sentimentScores: { pos: 0.02, neu: 0.11, neg: 0.87 },
    attachment: { name: "screenshot.png", type: "PNG", size: "1.2 MB" },
    createdAgo: "5h ago",
    createdAt: "2026-07-14T11:41:09Z",
    createdLabel: "TODAY 11:41 · 5H AGO",
  },
  {
    id: "f-003",
    ref: "FB-1041",
    feedbackId: "b47d20c9-8e15-4f7a-a6d3-0c92e84b5f71",
    title: "Add CSV export to reports",
    description: "Finance asks for monthly numbers; a one-click export would save time.",
    body: [
      "Finance asks for monthly numbers and today we screenshot the stats bar and retype them into a sheet.",
      "A one-click CSV export of the filtered list would save real time. Even just title, category, sentiment, and created date.",
    ],
    author: "Amina R.",
    category: "FEATURE",
    sentiment: "POS",
    sentimentScores: { pos: 0.78, neu: 0.19, neg: 0.03 },
    attachment: null,
    createdAgo: "Yesterday",
    createdAt: "2026-07-13T16:20:41Z",
    createdLabel: "YESTERDAY 16:20",
  },
  {
    id: "f-004",
    ref: "FB-1040",
    feedbackId: "e12a9d64-3c58-4b0f-91e7-6f48d20c3a95",
    title: "New standup format works",
    description: "Async check-ins freed up two hours a week for the whole team.",
    body: [
      "The async check-in format we trialed this sprint freed up roughly two hours a week for the whole team.",
      "Fewer interruptions, and the written updates double as a searchable log. Strong vote to keep it permanently.",
    ],
    author: "Maya T.",
    category: "PRAISE",
    sentiment: "POS",
    sentimentScores: { pos: 0.94, neu: 0.05, neg: 0.01 },
    attachment: null,
    createdAgo: "Yesterday",
    createdAt: "2026-07-13T09:15:27Z",
    createdLabel: "YESTERDAY 09:15",
  },
  {
    id: "f-005",
    ref: "FB-1039",
    feedbackId: "7a3f8b21-6d94-4c1e-8f52-b04e97a1d6c8",
    title: "Onboarding docs are outdated",
    description: "New joiners still get the 2024 setup guide; env vars changed since.",
    body: [
      "New joiners are still handed the 2024 setup guide. The environment variables and the local Docker steps have both changed since.",
      "Attached the current guide with the stale sections highlighted. Someone from platform should own a refresh.",
    ],
    author: "Dev H.",
    category: "PROCESS",
    sentiment: "NEU",
    sentimentScores: { pos: 0.12, neu: 0.71, neg: 0.17 },
    attachment: { name: "setup-guide.pdf", type: "PDF", size: "840 KB" },
    createdAgo: "2d ago",
    createdAt: "2026-07-12T13:04:11Z",
    createdLabel: "JUL 12 · 2D AGO",
  },
  {
    id: "f-006",
    ref: "FB-1038",
    feedbackId: "c95b4e07-2f6a-4d38-b1c9-84a0f7e52d36",
    title: "API docs page returns 404",
    description: "/docs/api broke after the last deploy; likely a routing issue.",
    body: [
      "/docs/api returns a 404 since the last deploy. External partners hit this page from the README link.",
      "Probably a routing issue: the docs moved under /developers but the old path never got a redirect.",
    ],
    author: "Priya S.",
    category: "BUG",
    sentiment: "NEG",
    sentimentScores: { pos: 0.03, neu: 0.24, neg: 0.73 },
    attachment: null,
    createdAgo: "3d ago",
    createdAt: "2026-07-11T10:52:48Z",
    createdLabel: "JUL 11 · 3D AGO",
  },
];

export const stats = [
  { label: "FEATURE", count: 24 },
  { label: "BUG", count: 13 },
  { label: "PROCESS", count: 8 },
  { label: "PRAISE", count: 11 },
];

export const sentimentSplit = { pos: 62, neu: 24, neg: 14 };

export const totalSubmissions = 56;
